// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobileGadgets.Infrastructure.Persistence;

#nullable disable

namespace MobileGadgets.Infrastructure.Migrations
{
    [DbContext(typeof(MobileGadgetsDbContext))]
    [Migration("20260901154926_AddBackgroundImages")]
    partial class AddBackgroundImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MobileGadgets.Domain.HeroGeneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomBackgroundImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeroModelId")
                        .HasColumnType("int");

                    b.Property<string>("OutputImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeroModelId");

                    b.HasIndex("SceneId");

                    b.ToTable("HeroGenerations");
                });

            modelBuilder.Entity("MobileGadgets.Domain.HeroModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CameraMaskImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DesignMaskImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverlayImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HeroModels");
                });

            modelBuilder.Entity("MobileGadgets.Domain.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MobileGadgets.Domain.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundBottomColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundTopColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CamY")
                        .HasColumnType("float");

                    b.Property<double>("CamZ")
                        .HasColumnType("float");

                    b.Property<string>("FloorBottomColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FloorTopColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Focal")
                        .HasColumnType("float");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<double>("LeanDegrees")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PitchDegrees")
                        .HasColumnType("float");

                    b.Property<string>("WallBottomColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WallTopColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("YawDegrees")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Scenes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundBottomColor = "#0c0b0b",
                            BackgroundTopColor = "#5a5654",
                            CamY = 1.3500000000000001,
                            CamZ = -2.1000000000000001,
                            FloorBottomColor = "#080707",
                            FloorTopColor = "#463e3a",
                            Focal = 1500.0,
                            IsDefault = true,
                            LeanDegrees = 5.0,
                            Name = "Dark Studio",
                            PitchDegrees = 9.0,
                            WallBottomColor = "#242221",
                            WallTopColor = "#686360",
                            YawDegrees = 0.0
                        },
                        new
                        {
                            Id = 2,
                            BackgroundBottomColor = "#e2e2de",
                            BackgroundTopColor = "#f4f4f2",
                            CamY = 1.3500000000000001,
                            CamZ = -2.1000000000000001,
                            FloorBottomColor = "#d6d6d2",
                            FloorTopColor = "#ffffff",
                            Focal = 1500.0,
                            IsDefault = false,
                            LeanDegrees = 5.0,
                            Name = "Light Studio",
                            PitchDegrees = 9.0,
                            WallBottomColor = "#ebebe8",
                            WallTopColor = "#faf9f7",
                            YawDegrees = 0.0
                        },
                        new
                        {
                            Id = 3,
                            BackgroundBottomColor = "#141416",
                            BackgroundImageUrl = "/uploads/seed-bg-warm-beige-studio.png",
                            BackgroundTopColor = "#2c2c2f",
                            CamY = 1.3500000000000001,
                            CamZ = -2.1000000000000001,
                            FloorBottomColor = "#111113",
                            FloorTopColor = "#333336",
                            Focal = 1500.0,
                            IsDefault = false,
                            LeanDegrees = 5.0,
                            Name = "Warm Beige Backdrop",
                            PitchDegrees = 9.0,
                            WallBottomColor = "#28282b",
                            WallTopColor = "#3d3d40",
                            YawDegrees = 0.0
                        },
                        new
                        {
                            Id = 4,
                            BackgroundBottomColor = "#141416",
                            BackgroundImageUrl = "/uploads/seed-bg-cool-slate-studio.png",
                            BackgroundTopColor = "#2c2c2f",
                            CamY = 1.3500000000000001,
                            CamZ = -2.1000000000000001,
                            FloorBottomColor = "#111113",
                            FloorTopColor = "#333336",
                            Focal = 1500.0,
                            IsDefault = false,
                            LeanDegrees = 5.0,
                            Name = "Cool Slate Backdrop",
                            PitchDegrees = 9.0,
                            WallBottomColor = "#28282b",
                            WallTopColor = "#3d3d40",
                            YawDegrees = 0.0
                        });
                });

            modelBuilder.Entity("MobileGadgets.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MobileGadgets.Domain.HeroGeneration", b =>
                {
                    b.HasOne("MobileGadgets.Domain.HeroModel", "HeroModel")
                        .WithMany()
                        .HasForeignKey("HeroModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobileGadgets.Domain.Scene", "Scene")
                        .WithMany()
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeroModel");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("MobileGadgets.Domain.RefreshToken", b =>
                {
                    b.HasOne("MobileGadgets.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
